#!/usr/bin/python3

from Robot import RobotControlInput


## The abstract superclass for robotic navitgation algorithms
#
class AbstractNavigationAlgorithm:

	## Initializes the navigation algorithm.
	# 
	# @param robot (Robot object)
	# <br>	-- the robot that this algorithm is navigating for
	#
	# @param cmdargs (object)
	# <br>	-- A command-line arguments object generated by `argparse`.
	# 
	def __init__(self, robot, cmdargs):
		self._robot = robot;
		self._cmdargs = cmdargs;


	## Select the next action for the robot
	#
	# This function uses the robot's radar and location information, as
	# well as internally stored information about previous locations,
	# to compute the next action the robot should take.
	#
	# @returns (`Robot.RobotControlInput` object)
	# <br>	-- A control input representing the next action the robot
	# 	should take.
	#
	def select_next_action(self):
		return RobotControlInput(0, 0);


	def has_given_up(self):
		return False;

